// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goapp/ent/accounting"
	"goapp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountingUpdate is the builder for updating Accounting entities.
type AccountingUpdate struct {
	config
	hooks    []Hook
	mutation *AccountingMutation
}

// Where appends a list predicates to the AccountingUpdate builder.
func (_u *AccountingUpdate) Where(ps ...predicate.Accounting) *AccountingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccountingUpdate) SetStatus(v int8) *AccountingUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountingUpdate) SetNillableStatus(v *int8) *AccountingUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AccountingUpdate) AddStatus(v int8) *AccountingUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountingUpdate) SetUpdatedAt(v time.Time) *AccountingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountingUpdate) SetName(v string) *AccountingUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountingUpdate) SetNillableName(v *string) *AccountingUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountingUpdate) SetDescription(v string) *AccountingUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountingUpdate) SetNillableDescription(v *string) *AccountingUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountingUpdate) ClearDescription() *AccountingUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the AccountingMutation object of the builder.
func (_u *AccountingUpdate) Mutation() *AccountingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accounting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountingUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accounting.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Accounting.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accounting.Table, accounting.Columns, sqlgraph.NewFieldSpec(accounting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accounting.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(accounting.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accounting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accounting.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(accounting.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(accounting.FieldDescription, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountingUpdateOne is the builder for updating a single Accounting entity.
type AccountingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountingMutation
}

// SetStatus sets the "status" field.
func (_u *AccountingUpdateOne) SetStatus(v int8) *AccountingUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccountingUpdateOne) SetNillableStatus(v *int8) *AccountingUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AccountingUpdateOne) AddStatus(v int8) *AccountingUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountingUpdateOne) SetUpdatedAt(v time.Time) *AccountingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AccountingUpdateOne) SetName(v string) *AccountingUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountingUpdateOne) SetNillableName(v *string) *AccountingUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AccountingUpdateOne) SetDescription(v string) *AccountingUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AccountingUpdateOne) SetNillableDescription(v *string) *AccountingUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AccountingUpdateOne) ClearDescription() *AccountingUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the AccountingMutation object of the builder.
func (_u *AccountingUpdateOne) Mutation() *AccountingMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountingUpdate builder.
func (_u *AccountingUpdateOne) Where(ps ...predicate.Accounting) *AccountingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountingUpdateOne) Select(field string, fields ...string) *AccountingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Accounting entity.
func (_u *AccountingUpdateOne) Save(ctx context.Context) (*Accounting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountingUpdateOne) SaveX(ctx context.Context) *Accounting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accounting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountingUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := accounting.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Accounting.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountingUpdateOne) sqlSave(ctx context.Context) (_node *Accounting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accounting.Table, accounting.Columns, sqlgraph.NewFieldSpec(accounting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Accounting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accounting.FieldID)
		for _, f := range fields {
			if !accounting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accounting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accounting.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(accounting.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accounting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(accounting.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(accounting.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(accounting.FieldDescription, field.TypeString)
	}
	_node = &Accounting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accounting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
